<a href="https://colab.research.google.com/github/darfisha/Numpy-Employee-Data-Analysis/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [ ]:
#PART 1 - INTRODUCTION TO NUMPY

In [ ]:
import numpy as np

In [ ]:
#1) creating 1D Array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
#2) creating 2D arrays
arr2D = np.array([[1,2],[3,4],[5,6]])
arr2D

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#3) creating arrays with specific values
zeros_arr = np.zeros([3,4])
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#4)Create an array with range of values
range_arr = np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [ ]:
#5)Create an with ones
ones_arr = np.ones([3,4])
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 6) empty
empty_arr = np.empty([3,4])
empty_arr

array([[0.3, 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 1. , 0.5, 1. ]])

In [ ]:
#Part 2 - SHAPE, SIZE, DIMENSIONS

#SHAPE = RETURNS THE DIMENSIONS OF THE ARRAY(ROWS, COLUMNS)
#SIZE = RETURNS THE TOTAL NUMBER OF ELEMENTS IN THE ARRAY
#nDIM = RETUENS THE NUMBER OF DIMENSIONS OF THE ARRAY
#dtype = returns the data type of the elements

In [ ]:
a = np.array([[1,2,],[2,3],[3,4]])
a
print("Shape =",a.shape)
print("size =", a.size)
print("dimension =",a.ndim)
print("type =", a.dtype)

Shape = (3, 2)
size = 6
dimension = 2
type = int64


In [ ]:
# Task create a 3x3 array and print its shape size dim and data type

In [ ]:
b= np.array([[[1,2],[2,3]],[[3,4],[4,5]],[[5,6],[3,5]]])
b

print("Shape =",b.shape)
print("size =", b.size)
print("dimension =",b.ndim)
print("type =", b.dtype)

Shape = (3, 2, 2)
size = 12
dimension = 3
type = int64


In [ ]:
#PART 3 - SLICING AND INDEXING

In [ ]:
#1) Indexing in 1D
a = np.array([1,2,3,5,6,8])
a[3]
a[2:4]

array([3, 5])

In [ ]:
#Select values based on conditions
import numpy as np
a = np.array([100,200,300,400,500,600])
a[a>300]
a[[1,3]]

array([200, 400])

In [ ]:
a = np.array([100,200,300,400,500,600])
a[-1]

np.int64(600)

In [ ]:
#2) Indexing in 2D
b = np.array([[2,3],[1,5],[3,4],[6,8]])
b[1,1]

np.int64(5)

In [ ]:
b = array_3d = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]])
#slice the first 2 rows and first 2 columns
b[:2,:2]

array([[1, 2],
       [5, 6]])

In [ ]:
#PART 4 - ARRAY OPERATIONS
arr = np.array([0,1,2,3,4,5])
#adding 5 to each element
arr+5
arr/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
#universal functions
np.add(arr, 2)
np.multiply(arr, 5)
np.subtract(arr, 2)
np.divide(arr, 2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
#PART 5 - Flatten, ravel

In [ ]:
#flatten - converts multi dimensional arrays into one dimension array
b = np.array([[2,3],[1,5],[3,4],[6,8]])
flat = b.flatten()
flat

array([2, 3, 1, 5, 3, 4, 6, 8])

In [ ]:
# ravel - returns the flatten array without copy (modyfying it can affect the
# orignal array)
print(b.ravel())
b

[2 3 1 5 3 4 6 8]


array([[2, 3],
       [1, 5],
       [3, 4],
       [6, 8]])

In [ ]:
flat[0] = 99
print("Modified flattened view:", flat)
print("Modified original array:\n", b)


Modified flattened view: [99  3  1  5  3  4  6  8]
Modified original array:
 [[2 3]
 [1 5]
 [3 4]
 [6 8]]


In [ ]:
flat.base is b
#If it returns True, flat is a view (modifying it will affect b). If False, it's a copy.


False

In [ ]:
#PART 6 - RANDOM OPERATIONS
#1) generate random values from (0,1)
print(np.random.rand(2,4))

[[0.11740554 0.07007067 0.14285289 0.13662574]
 [0.13370499 0.92205521 0.94973508 0.55026094]]


In [ ]:
#2) generate random integers
print(np.random.randint(1,10,6))

[4 6 1 4 5 8]


In [ ]:
#3) generate random numbers from normal distribuion
np.random.normal(0,1,(2,2))

#Mean = 0
#Standard deviation = 1
#Shape = (2, 2) → 2 rows, 2 column

array([[ 1.2247433 ,  1.02214827],
       [-0.54761923, -0.88892018]])

In [ ]:
#Part 7) String operation
str = np.array(["data", "Numpy", "Python"])
print(np.char.lower(str))
print(np.char.upper(str))
print(np.char.capitalize(str))
print(np.char.add(str[0], "science"))
print(np.char.replace(str, "a", "@"))

['data' 'numpy' 'python']
['DATA' 'NUMPY' 'PYTHON']
['Data' 'Numpy' 'Python']
datascience
['d@t@' 'Numpy' 'Python']


In [ ]:
#PART 8)advance numpy topics

#1) reshape() - change the shape of the array without changing its data
arr = np.arange(6)
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
#2) resize = changes the shape and modifiesb the orignal array if new size > orignal, it fills with garbage values.
arr = np.arange(6)
np.resize(arr, (3,3))

#Garbage values are like random leftover junk in memory that you didn't ask for.
#Random values are like numbers you purposefully ask the computer to generate, and they're following a rule.

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
#3) Transpose or .T = FLIPS ROWS AND COLUMNS
arr = np.array([[0,1,2],[3,4,5]])
arr
print(arr.transpose())

[[0 3]
 [1 4]
 [2 5]]


In [ ]:
a = np.array([1,2,3,4])
print(a.transpose())

#In NumPy, the transpose() method is used to transpose a multi-dimensional array, meaning it switches rows with columns

array([1, 2, 3, 4])

In [ ]:
#reshaping
b=a.reshape(-1,1)
print(b.transpose())

[[1 2 3 4]]


In [ ]:
#PART 9 - BROADCASTING, AXIS BASED OPERATIIONS
a = np.array([[1,2,3],[4,7,8]])
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[ 5  9 11]
[ 6 19]


In [ ]:
#Sorting And Searching
#sort - sort the array
#argsort - return indices of the sorted arrays
#where - return indices where a condition is true
arr = np.array([0,3,2,3,9,5])
np.sort(arr)
np.argsort(arr)
np.where(arr>3)

(array([4, 5]),)

In [ ]:
#Set operations
a = np.array([0,1,2,2,3])
b = np.array([3,4,5,6])
np.unique(a)
np.intersect1d(a,b)
np.union1d(a,b)

array([0, 1, 2])

TEST

In [3]:
import pandas as pd
df = pd.read_csv("/content/employee.csv")
df

empid empfirstname emplastname    sal dateofbirth           city  deptid  \
0     101         John         Doe  75000  15-05-1990       New York     101   
1     102         Jane       Smith  65000  23-08-1988  San Francisco     102   
2     103      Michael     Johnson  80000  10-02-1985        Chicago     101   
3     104        Emily    Williams  70000  30-11-1992    Los Angeles     103   
4     105       Robert      Miller  90000  18-07-1980        Seattle     102   
5     106        Alice     Jackson  72000  05-04-1995          Miami     104   
6     107        David    Anderson  85000  12-09-1987         Dallas     101   
7     108       Olivia      Thomas  78000  08-12-1991        Houston     103   
8     109      William       Brown  95000  25-06-1982        Phoenix     102   
9     110       Sophia       White  68000  14-08-1993        Atlanta     104   
10    111        James       Clark  89000  22-03-1984         Denver     101   
11    112         Emma        Hall  82000  17-01-1994       Portland     103   
12    113  Christopher       Young  76000  03-07-1989      San Diego     102   
13    114     Isabella        Hill  91000  20-04-1983        Orlando     101   
14    115        Aiden        Ward  69000  15-11-1996          Tampa     104   
15    116      Abigail      Turner  80000  28-02-1986         Austin     103   
16    117         Liam      Carter  74000  05-09-1997    Minneapolis     102   
17    118         Ella        Ross  92000  10-05-1981      Charlotte     101   
18    119      Jackson      Martin  67000  18-03-1998        Raleigh     104   
19    120        Sofia      Cooper  88000  01-12-1988     Sacramento     103   

           deptname  
0       Engineering  
1         Marketing  
2       Engineering  
3   Human Resources  
4         Marketing  
5           Finance  
6       Engineering  
7   Human Resources  
8         Marketing  
9           Finance  
10      Engineering  
11  Human Resources  
12        Marketing  
13      Engineering  
14          Finance  
15  Human Resources  
16        Marketing  
17      Engineering  
18          Finance  
19  Human Resources

In [ ]:
import numpy as np

In [4]:
dfnew = np.array(df)
dfnew

array([[101, 'John', 'Doe', 75000, '15-05-1990', 'New York', 101,
        'Engineering'],
       [102, 'Jane', 'Smith', 65000, '23-08-1988', 'San Francisco', 102,
        'Marketing'],
       [103, 'Michael', 'Johnson', 80000, '10-02-1985', 'Chicago', 101,
        'Engineering'],
       [104, 'Emily', 'Williams', 70000, '30-11-1992', 'Los Angeles',
        103, 'Human Resources'],
       [105, 'Robert', 'Miller', 90000, '18-07-1980', 'Seattle', 102,
        'Marketing'],
       [106, 'Alice', 'Jackson', 72000, '05-04-1995', 'Miami', 104,
        'Finance'],
       [107, 'David', 'Anderson', 85000, '12-09-1987', 'Dallas', 101,
        'Engineering'],
       [108, 'Olivia', 'Thomas', 78000, '08-12-1991', 'Houston', 103,
        'Human Resources'],
       [109, 'William', 'Brown', 95000, '25-06-1982', 'Phoenix', 102,
        'Marketing'],
       [110, 'Sophia', 'White', 68000, '14-08-1993', 'Atlanta', 104,
        'Finance'],
       [111, 'James', 'Clark', 89000, '22-03-1984', 'Denver', 1

In [5]:
df.head()

empid empfirstname emplastname    sal dateofbirth           city  deptid  \
0    101         John         Doe  75000  15-05-1990       New York     101   
1    102         Jane       Smith  65000  23-08-1988  San Francisco     102   
2    103      Michael     Johnson  80000  10-02-1985        Chicago     101   
3    104        Emily    Williams  70000  30-11-1992    Los Angeles     103   
4    105       Robert      Miller  90000  18-07-1980        Seattle     102   

          deptname  
0      Engineering  
1        Marketing  
2      Engineering  
3  Human Resources  
4        Marketing

In [ ]:
df[df["sal"] > 70000]

empid empfirstname emplastname    sal dateofbirth         city  deptid  \
0     101         John         Doe  75000  15-05-1990     New York     101   
2     103      Michael     Johnson  80000  10-02-1985      Chicago     101   
4     105       Robert      Miller  90000  18-07-1980      Seattle     102   
5     106        Alice     Jackson  72000  05-04-1995        Miami     104   
6     107        David    Anderson  85000  12-09-1987       Dallas     101   
7     108       Olivia      Thomas  78000  08-12-1991      Houston     103   
8     109      William       Brown  95000  25-06-1982      Phoenix     102   
10    111        James       Clark  89000  22-03-1984       Denver     101   
11    112         Emma        Hall  82000  17-01-1994     Portland     103   
12    113  Christopher       Young  76000  03-07-1989    San Diego     102   
13    114     Isabella        Hill  91000  20-04-1983      Orlando     101   
15    116      Abigail      Turner  80000  28-02-1986       Austin     103   
16    117         Liam      Carter  74000  05-09-1997  Minneapolis     102   
17    118         Ella        Ross  92000  10-05-1981    Charlotte     101   
19    120        Sofia      Cooper  88000  01-12-1988   Sacramento     103   

           deptname  
0       Engineering  
2       Engineering  
4         Marketing  
5           Finance  
6       Engineering  
7   Human Resources  
8         Marketing  
10      Engineering  
11  Human Resources  
12        Marketing  
13      Engineering  
15  Human Resources  
16        Marketing  
17      Engineering  
19  Human Resources

In [ ]:
df[df["sal"]>70000].sort_values("sal", ascending=False).head(3)

empid empfirstname emplastname    sal dateofbirth       city  deptid  \
8     109      William       Brown  95000  25-06-1982    Phoenix     102   
17    118         Ella        Ross  92000  10-05-1981  Charlotte     101   
13    114     Isabella        Hill  91000  20-04-1983    Orlando     101   

       deptname  
8     Marketing  
17  Engineering  
13  Engineering

In [ ]:
df[df["dateofbirth"] > np.datetime64('31-12-1989')]

ValueError: Error parsing datetime string "31-12-1989" at position 8

In [ ]:
import pandas as pd
df["dateofbirth"] = pd.to_datetime(df["dateofbirth"])

df[df["dateofbirth"] > pd.Timestamp('1989-12-31')]

empid empfirstname emplastname    sal dateofbirth         city  deptid  \
0     101         John         Doe  75000  1990-05-15     New York     101   
3     104        Emily    Williams  70000  1992-11-30  Los Angeles     103   
5     106        Alice     Jackson  72000  1995-04-05        Miami     104   
7     108       Olivia      Thomas  78000  1991-12-08      Houston     103   
9     110       Sophia       White  68000  1993-08-14      Atlanta     104   
11    112         Emma        Hall  82000  1994-01-17     Portland     103   
14    115        Aiden        Ward  69000  1996-11-15        Tampa     104   
16    117         Liam      Carter  74000  1997-09-05  Minneapolis     102   
18    119      Jackson      Martin  67000  1998-03-18      Raleigh     104   

           deptname  
0       Engineering  
3   Human Resources  
5           Finance  
7   Human Resources  
9           Finance  
11  Human Resources  
14          Finance  
16        Marketing  
18          Finance

In [ ]:
df.groupby("deptname").sum("sal")

empid     sal  deptid
deptname                              
Engineering        654  512000     606
Finance            450  276000     416
Human Resources    560  398000     515
Marketing          546  400000     510

In [8]:
from datetime import datetime, date
import pandas as pd
today = '05-12-2025'
# Convert today to datetime object first
today_date = datetime.strptime(today, '%m-%d-%Y').date()
#Ensure 'dateofbirth' column is in datetime format
df['dateofbirth'] = pd.to_datetime(df['dateofbirth'])
#Now calculate the difference in days
df['age_in_days'] = today_date - df['dateofbirth'].dt.date
# Convert age in days to age in years
df['age_in_years'] = df['age_in_days'] / pd.Timedelta(days=365.2425)
df[['dateofbirth', 'age_in_days', 'age_in_years']]

<ipython-input-8-04d28d2b0ac2>:7: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['dateofbirth'] = pd.to_datetime(df['dateofbirth'])


dateofbirth          age_in_days  age_in_years
0   1990-05-15  12781 days, 0:00:00     34.993189
1   1988-08-23  13411 days, 0:00:00     36.718071
2   1985-02-10  14701 days, 0:00:00     40.249971
3   1992-11-30  11851 days, 0:00:00     32.446936
4   1980-07-18  16369 days, 0:00:00     44.816800
5   1995-04-05  10995 days, 0:00:00     30.103288
6   1987-09-12  13757 days, 0:00:00     37.665387
7   1991-12-08  12209 days, 0:00:00     33.427107
8   1982-06-25  15662 days, 0:00:00     42.881100
9   1993-08-14  11594 days, 0:00:00     31.743294
10  1984-03-22  15026 days, 0:00:00     41.139791
11  1994-01-17  11438 days, 0:00:00     31.316180
12  1989-07-03  13097 days, 0:00:00     35.858368
13  1983-04-20  15363 days, 0:00:00     42.062465
14  1996-11-15  10405 days, 0:00:00     28.487922
15  1986-02-28  14318 days, 0:00:00     39.201353
16  1997-09-05  10111 days, 0:00:00     27.682978
17  1981-05-10  16073 days, 0:00:00     44.006379
18  1998-03-18   9917 days, 0:00:00     27.151824
19  1988-12-01  13311 days, 0:00:00     36.444280

In [7]:
a = df["sal"].sum()
a
b = df["empid"].count()
b
c = a/b

print("Average salary of employees is", c )

Average salary of employees is 79300.0


In [11]:
df["city"].unique()

array(['New York', 'San Francisco', 'Chicago', 'Los Angeles', 'Seattle',
       'Miami', 'Dallas', 'Houston', 'Phoenix', 'Atlanta', 'Denver',
       'Portland', 'San Diego', 'Orlando', 'Tampa', 'Austin',
       'Minneapolis', 'Charlotte', 'Raleigh', 'Sacramento'], dtype=object)

TypeError: can only concatenate str (not "int") to str

In [17]:
# prompt: #increase the salary of employees in the marketing department by 10% using

import pandas as pd

# Load the dataframe.
df = pd.read_csv("/content/employee.csv")


# Filter for the marketing department and increase their salary by 10%.
df.loc[df['deptname'] == 'Marketing', 'sal'] *= 1.10

# Display the updated dataframe.
df


<ipython-input-17-59b9936b08ff>:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 71500.  99000. 104500.  83600.  81400.]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['deptname'] == 'Marketing', 'sal'] *= 1.10


empid empfirstname emplastname       sal dateofbirth           city  \
0     101         John         Doe   75000.0  15-05-1990       New York   
1     102         Jane       Smith   71500.0  23-08-1988  San Francisco   
2     103      Michael     Johnson   80000.0  10-02-1985        Chicago   
3     104        Emily    Williams   70000.0  30-11-1992    Los Angeles   
4     105       Robert      Miller   99000.0  18-07-1980        Seattle   
5     106        Alice     Jackson   72000.0  05-04-1995          Miami   
6     107        David    Anderson   85000.0  12-09-1987         Dallas   
7     108       Olivia      Thomas   78000.0  08-12-1991        Houston   
8     109      William       Brown  104500.0  25-06-1982        Phoenix   
9     110       Sophia       White   68000.0  14-08-1993        Atlanta   
10    111        James       Clark   89000.0  22-03-1984         Denver   
11    112         Emma        Hall   82000.0  17-01-1994       Portland   
12    113  Christopher       Young   83600.0  03-07-1989      San Diego   
13    114     Isabella        Hill   91000.0  20-04-1983        Orlando   
14    115        Aiden        Ward   69000.0  15-11-1996          Tampa   
15    116      Abigail      Turner   80000.0  28-02-1986         Austin   
16    117         Liam      Carter   81400.0  05-09-1997    Minneapolis   
17    118         Ella        Ross   92000.0  10-05-1981      Charlotte   
18    119      Jackson      Martin   67000.0  18-03-1998        Raleigh   
19    120        Sofia      Cooper   88000.0  01-12-1988     Sacramento   

    deptid         deptname  
0      101      Engineering  
1      102        Marketing  
2      101      Engineering  
3      103  Human Resources  
4      102        Marketing  
5      104          Finance  
6      101      Engineering  
7      103  Human Resources  
8      102        Marketing  
9      104          Finance  
10     101      Engineering  
11     103  Human Resources  
12     102        Marketing  
13     101      Engineering  
14     104          Finance  
15     103  Human Resources  
16     102        Marketing  
17     101      Engineering  
18     104          Finance  
19     103  Human Resources

In [25]:
df.sort_values(by = ["sal"] , ascending=False)[["empfirstname", "sal"]].head(3)

empfirstname       sal
8       William  104500.0
4        Robert   99000.0
17         Ella   92000.0

In [26]:
# Convert 'dateofbirth' to datetime objects for proper comparison
df['dateofbirth'] = pd.to_datetime(df['dateofbirth'])

# Filter employees born before 1990 and update their salary
df.loc[df['dateofbirth'] < pd.Timestamp('1990-01-01'), 'sal'] = 80000

# Display the updated dataframe
df

<ipython-input-26-1f493bd3afd7>:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['dateofbirth'] = pd.to_datetime(df['dateofbirth'])


empid empfirstname emplastname      sal dateofbirth           city  \
0     101         John         Doe  75000.0  1990-05-15       New York   
1     102         Jane       Smith  80000.0  1988-08-23  San Francisco   
2     103      Michael     Johnson  80000.0  1985-02-10        Chicago   
3     104        Emily    Williams  70000.0  1992-11-30    Los Angeles   
4     105       Robert      Miller  80000.0  1980-07-18        Seattle   
5     106        Alice     Jackson  72000.0  1995-04-05          Miami   
6     107        David    Anderson  80000.0  1987-09-12         Dallas   
7     108       Olivia      Thomas  78000.0  1991-12-08        Houston   
8     109      William       Brown  80000.0  1982-06-25        Phoenix   
9     110       Sophia       White  68000.0  1993-08-14        Atlanta   
10    111        James       Clark  80000.0  1984-03-22         Denver   
11    112         Emma        Hall  82000.0  1994-01-17       Portland   
12    113  Christopher       Young  80000.0  1989-07-03      San Diego   
13    114     Isabella        Hill  80000.0  1983-04-20        Orlando   
14    115        Aiden        Ward  69000.0  1996-11-15          Tampa   
15    116      Abigail      Turner  80000.0  1986-02-28         Austin   
16    117         Liam      Carter  81400.0  1997-09-05    Minneapolis   
17    118         Ella        Ross  80000.0  1981-05-10      Charlotte   
18    119      Jackson      Martin  67000.0  1998-03-18        Raleigh   
19    120        Sofia      Cooper  80000.0  1988-12-01     Sacramento   

    deptid         deptname  
0      101      Engineering  
1      102        Marketing  
2      101      Engineering  
3      103  Human Resources  
4      102        Marketing  
5      104          Finance  
6      101      Engineering  
7      103  Human Resources  
8      102        Marketing  
9      104          Finance  
10     101      Engineering  
11     103  Human Resources  
12     102        Marketing  
13     101      Engineering  
14     104          Finance  
15     103  Human Resources  
16     102        Marketing  
17     101      Engineering  
18     104          Finance  
19     103  Human Resources

In [34]:
df.groupby("deptname")["sal"].agg(["mean", "median"])

mean   median
deptname                              
Engineering      85333.333333  87000.0
Finance          69000.000000  68500.0
Human Resources  79600.000000  80000.0
Marketing        80000.000000  76000.0

In [35]:
df.groupby("city")["empid"].count()

city
Atlanta          1
Austin           1
Charlotte        1
Chicago          1
Dallas           1
Denver           1
Houston          1
Los Angeles      1
Miami            1
Minneapolis      1
New York         1
Orlando          1
Phoenix          1
Portland         1
Raleigh          1
Sacramento       1
San Diego        1
San Francisco    1
Seattle          1
Tampa            1
Name: empid, dtype: int64

In [38]:
df[["empfirstname", "emplastname", "sal" ]]

empfirstname emplastname    sal
0          John         Doe  75000
1          Jane       Smith  65000
2       Michael     Johnson  80000
3         Emily    Williams  70000
4        Robert      Miller  90000
5         Alice     Jackson  72000
6         David    Anderson  85000
7        Olivia      Thomas  78000
8       William       Brown  95000
9        Sophia       White  68000
10        James       Clark  89000
11         Emma        Hall  82000
12  Christopher       Young  76000
13     Isabella        Hill  91000
14        Aiden        Ward  69000
15      Abigail      Turner  80000
16         Liam      Carter  74000
17         Ella        Ross  92000
18      Jackson      Martin  67000
19        Sofia      Cooper  88000

In [48]:
a = df[(df["sal"] > 60000) & (df["sal"] < 80000)]["empfirstname"].count()
print( "total number of employees having salary between 60000 and 80000 is", a)

total number of employees having salary between 60000 and 80000 is 10


In [57]:
sal = df[df["sal"] > 60000]

# Step 2: Group by deptname and sort by salary in descending order
sorted_sal = sal.sort_values("sal", ascending=False).groupby("deptname").head(1)

# Print the result
print(sorted_sal)

    empid empfirstname emplastname    sal dateofbirth        city  deptid  \
8     109      William       Brown  95000  25-06-1982     Phoenix     102   
17    118         Ella        Ross  92000  10-05-1981   Charlotte     101   
19    120        Sofia      Cooper  88000  01-12-1988  Sacramento     103   
5     106        Alice     Jackson  72000  05-04-1995       Miami     104   

           deptname  
8         Marketing  
17      Engineering  
19  Human Resources  
5           Finance  
